use Mix.Config
import System, only: [get_env: 1]
require Logger

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :classlab, Classlab.Endpoint,
  http: [port: get_env("PORT") || 80],
  url: [scheme: get_env("CLASSLAB_URL_SCHEME") || "http",
        host: get_env("CLASSLAB_URL_HOST") || "example.com",
        port: get_env("CLASSLAB_URL_PORT") || get_env("PORT") || 80],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: get_env("SECRET_KEY_BASE") || Logger.info("Please set env variable SECRET_KEY_BASE"),
  check_origin: false,
  debug_errors: true,
  server: true

# Do not print debug messages in production
# config :logger, level: :info
config :logger, level: :debug

config :phoenix, :stacktrace_depth, 20


# JWT secret for signing session token
config :classlab, :jwt_secret, get_env("SECRET_KEY_BASE")

# SMTP configuration
config :classlab, Classlab.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: get_env("CLASSLAB_SMTP_SERVER") || Logger.info("Please set env variable CLASSLAB_SMTP_SERVER"),
  port: 2525,
  username: get_env("CLASSLAB_SMTP_USERNAME") || Logger.info("Please set env variable CLASSLAB_SMTP_USERNAME"),
  password: get_env("CLASSLAB_SMTP_PASSWORD") || Logger.info("Please set env variable CLASSLAB_SMTP_PASSWORD"),
  tls: :if_available, # can be `:always` or `:never`
  ssl: false, # can be `true`
  retries: 1

# Email configuration
config :classlab, Classlab.Mailer,
  from_email: get_env("CLASSLAB_EMAIL_FROM_EMAIL") || Logger.info("Please set env variable CLASSLAB_EMAIL_FROM_EMAIL"),
  from_name: get_env("CLASSLAB_EMAIL_FROM_NAME") || Logger.info("Please set env variable CLASSLAB_EMAIL_FROM_NAME")

# Configure your database
config :classlab, Classlab.Repo,
  adapter: Ecto.Adapters.MySQL,
  username: get_env("DATABASE_MYSQL_USERNAME") || "root",
  password: get_env("DATABASE_MYSQL_PASSWORD") || "",
  database: get_env("DATABASE_MYSQL_DATABASE") || "classlab_prod",
  hostname: get_env("DATABASE_MYSQL_HOSTNAME") || "localhost",
  pool_size: get_env("DATABASE_MYSQL_POOLSIZE") || 20
